# Generated by Django 5.0.1 on 2024-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/brand_photo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
